name: Deploy Databricks Bundle to DEV Environment

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      

jobs:
  push_bundle:
    if: github.event.pull_request.merged == true
    name: "Development: Deploy Databricks Bundle"
    runs-on: ubuntu-latest

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy -t development
        working-directory: .
        env:
          DATABRICKS_BUNDLE_ENV: development
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_URL_DEV }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_SP_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_SP_SECRET }}
